package vista;

public class vista extends javax.swing.JFrame {
    
    //Valores de tamaño de ventana cambiar si se cambia diseño
    public final int height = 720;
    public final int width = 1280;
    
    //Valores de tamaño de panel main
    public final int heightMain = 720;
    public final int widthMain = 1280;
 
    public vista() {
        initComponents();
        this.setLocationRelativeTo(this);
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        main = new javax.swing.JPanel();
        recordatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudentMate");
        setResizable(false);

        menu.setBackground(new java.awt.Color(102, 153, 255));
        menu.setPreferredSize(new java.awt.Dimension(1270, 720));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 0));

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(main);

        recordatorios.setText("Recordatorios");
        recordatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recordatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(recordatorios)
                .addContainerGap(1095, Short.MAX_VALUE))
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(recordatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(menu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recordatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recordatoriosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recordatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel main;
    private javax.swing.JPanel menu;
    public javax.swing.JButton recordatorios;
    // End of variables declaration//GEN-END:variables
}
