package vista;

public class vista extends javax.swing.JFrame {
    
    //Valores de tamaño de ventana cambiar si se cambia diseño
    public final int height = 720;
    public final int width = 1280;
    
    //Valores de tamaño de panel main
    public final int heightMain = 720;
    public final int widthMain = 1280;
    
    public void init(){
        this.setVisible(true);
        this.reset();
    }
    
    public void reset(){
        //Para repintar si añaden componentes depues
        this.revalidate();
        this.repaint();
    }
    
    public vista() {
        initComponents();
        this.setLocationRelativeTo(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("StudentMate");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);

        menu.setBackground(new java.awt.Color(102, 153, 255));
        menu.setPreferredSize(new java.awt.Dimension(1270, 720));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(0, 0));

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setLayout(null);
        jScrollPane1.setViewportView(main);

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuLayout.createSequentialGroup()
                .addGap(0, 120, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(menu, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel main;
    private javax.swing.JPanel menu;
    // End of variables declaration//GEN-END:variables
}
