package vista.asignaturas;

public class AgregarAsignatura extends javax.swing.JDialog {

    /**
     * Creates new form agregarRecordatorio
     */
    public AgregarAsignatura() {
        initComponents();
        nombreWarn.setVisible(false);
        codigoWarn.setVisible(false);
        profesorWarn.setVisible(false);
        creditosWarn.setVisible(false);
        edificioWarn.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        agregar = new javax.swing.JButton();
        nombreWarn = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        profesor = new javax.swing.JTextField();
        creditos = new javax.swing.JTextField();
        edificio = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        codigoWarn = new javax.swing.JLabel();
        profesorWarn = new javax.swing.JLabel();
        creditosWarn = new javax.swing.JLabel();
        edificioWarn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 55, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Código");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 111, -1, -1));

        agregar.setText("Agregar");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jPanel1.add(agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        nombreWarn.setForeground(new java.awt.Color(204, 0, 0));
        nombreWarn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreWarn.setLabelFor(nombre);
        nombreWarn.setText("Ingrese un nombre");
        jPanel1.add(nombreWarn, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 80, 209, -1));

        nombre.setToolTipText("");
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 52, 209, -1));
        nombre.getAccessibleContext().setAccessibleDescription("");

        codigo.setToolTipText("");
        jPanel1.add(codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 108, 209, -1));

        profesor.setToolTipText("");
        jPanel1.add(profesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 166, 209, -1));

        creditos.setToolTipText("");
        jPanel1.add(creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 222, 209, -1));

        edificio.setToolTipText("");
        jPanel1.add(edificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 278, 209, -1));
        edificio.getAccessibleContext().setAccessibleDescription("");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Creditos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 225, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Edificio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 278, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Profesor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 169, -1, -1));

        codigoWarn.setForeground(new java.awt.Color(204, 0, 0));
        codigoWarn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codigoWarn.setLabelFor(codigo);
        codigoWarn.setText("Ingrese un codigo");
        nombreWarn.setVisible(false);
        jPanel1.add(codigoWarn, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 136, 209, -1));

        profesorWarn.setForeground(new java.awt.Color(204, 0, 0));
        profesorWarn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profesorWarn.setLabelFor(profesor);
        profesorWarn.setText("Ingrese profesor");
        nombreWarn.setVisible(false);
        jPanel1.add(profesorWarn, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 194, 209, -1));

        creditosWarn.setForeground(new java.awt.Color(204, 0, 0));
        creditosWarn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        creditosWarn.setLabelFor(creditos);
        creditosWarn.setText("Ingrese un creditos validos");
        nombreWarn.setVisible(false);
        jPanel1.add(creditosWarn, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 250, 209, -1));

        edificioWarn.setForeground(new java.awt.Color(204, 0, 0));
        edificioWarn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        edificioWarn.setLabelFor(edificio);
        edificioWarn.setText("Ingrese un edificio");
        nombreWarn.setVisible(false);
        jPanel1.add(edificioWarn, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 306, 209, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregar;
    public javax.swing.JTextField codigo;
    public javax.swing.JLabel codigoWarn;
    public javax.swing.JTextField creditos;
    public javax.swing.JLabel creditosWarn;
    public javax.swing.JTextField edificio;
    public javax.swing.JLabel edificioWarn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField nombre;
    public javax.swing.JLabel nombreWarn;
    public javax.swing.JTextField profesor;
    public javax.swing.JLabel profesorWarn;
    // End of variables declaration//GEN-END:variables
}
