package vista.recordatorio;

import java.awt.Color;
import modelo.Recordatorio;

public class RecordatorioUnit extends javax.swing.JPanel {
    
    public Recordatorio info;
    public final int WIDTH = 900;
    public final int HEIGHT = 180;
   
    public RecordatorioUnit(Recordatorio record) {
        this.info = record;
        initComponents();
        updateInfo();
    }
    
    public void updateInfo(){
        titulo.setText(info.getTitulo());
        descripcion.setText(info.getDescripcion());
        fecha.setText(info.getFechaHora() == null ? "" : info.getFechaHora().toString().substring(0, 10));
        if(fecha.getText().isEmpty()) fecha.setVisible(false);
        if(info.isCompletado()) {
            this.setBackground(Color.getHSBColor(125 / 360.0f,0.25f ,0.92f));
            this.checkButton.setBackground(Color.getHSBColor(125 / 360.0f,0.25f ,0.92f));
            checkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/notcheckButton.png")));
        }else {
            this.setBackground(Color.WHITE);
            this.checkButton.setBackground(Color.WHITE);
            checkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkButton.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        checkButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        titulo.setBackground(new java.awt.Color(0, 0, 0));
        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setText("Ti");

        fecha.setForeground(new java.awt.Color(51, 51, 51));
        fecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fecha.png"))); // NOI18N

        descripcion.setEditable(false);
        descripcion.setBackground(new java.awt.Color(255, 255, 255));
        descripcion.setColumns(20);
        descripcion.setForeground(new java.awt.Color(0, 255, 0));
        descripcion.setRows(5);
        descripcion.setBorder(null);
        descripcion.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        descripcion.setEnabled(false);
        jScrollPane2.setViewportView(descripcion);

        checkButton.setBackground(new java.awt.Color(255, 255, 255));
        checkButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/checkButton.png"))); // NOI18N
        checkButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        checkButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        deleteButton.setText("Borrar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(checkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fecha)
                    .addComponent(deleteButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton checkButton;
    public javax.swing.JButton deleteButton;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel fecha;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
